def WipeUp(Width, Height, Display):
    Display.fill(0)
    Display.fill_rect(0, 0, Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/8), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4)+int(Height/8), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4*2), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4*2)+int(Height/8), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4*3), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4*3)+int(Height/8), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()
    Display.fill(0)
    Display.fill_rect(0, int(Height/4*4), Width, int(Height/4), 1)
    time.sleep(0.01)
    Display.show()